server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yusufcandmrz/micro-hub-config.git
          clone-on-start: true
          default-label: master
